### ISSUE TITLE
R2RML rr:template and rr:dataType syntax 

### ISSUE THREAD

**Issue by martinbog** [nkons/r2rml-parser#13]
Hi,

When I'm creating a template (rr:template in the mapping file) I've some trouble with special characters.

That's the mapping :

----------------
```
map:fixes
	a rr::TriplesMap;
	rr:logicalTable [ 
                rr:sqlQuery """ SELECT id, lon, lat FROM geolifemini """ ; 
        ];
	rr:subjectMap [
 		rr:template 'http://wstraj.com/fix/{id}';
		rr:class traj:Fix;
	 ];
	rr:predicateObjectMap [
		rr:predicate geo:geometry;
		rr:objectMap[
			rr:template 'POINT({lon},{lat});http://www.opengis.net/ref/def/crs/EPSG/0/4326"^^<http://strdf.di.uoa.gr/ontology#WKT>';
		 ];
	].
```
----------------

That's part of the result :

----------------
```
<http://wstraj.com/fix/15>
        a             traj:Fix ;
        geo:geometry  "POINT(116.313862,40.010061);http://www.opengis.net/ref/def/crs/EPSG/0/4326"^^<http://strdf.di.uoa.gr/ontology#WKT%3E" .
```
----------------

That's what I would like to have as result :
```
<http://wstraj.com/fix/15>
        a             traj:Fix ;
        geo:geometry  "POINT(116.313862,40.010061);http://www.opengis.net/ref/def/crs/EPSG/0/4326"^^<http://strdf.di.uoa.gr/ontology#WKT> .
```
As so you might see, What I want is Double quotes between "POINT ... /0/4326" and not surrounding the whole object.

So my problems are the followings :

1. Is it possible to have rr:template to create result without automatically creating double quote " " ?

example : What I get : <subject> predicate "object".
                What I want : <subject> predicate object . (no double quotes)

2. In my previous result, I get : ...#WKT%3E" and I'm trying to have ...#WKT>. I can't find a way to display this symbol : '>'.

Thanks in advance for your reply

**Comment by nkons** [comment]
Hi Martin, 

Thanks for your question.

Some thoughts, as I do not have the full picture:

1. You are trying to create a typed literal (i.e. something in the form "example"^^xsd:gYear

The current implementation only supports so far xsd datatypes. So, what you want to do should be like:

rr:objectMap[
            rr:template "POINT({lon},{lat});http://www.opengis.net/ref/def/crs/EPSG/0/4326";
            rr:datatype <http://strdf.di.uoa.gr/ontology#WKT>;
         ];

Currently, only xsd datatypes are supported (using Jena's com.hp.hpl.jena.datatypes.BaseDatatype), otherwise the parser throws an exception.

So: the part of the result that is after the ^^ should not be part of the template, it is the literal's datatype. R2RML Parser currently only supports XSD datatypes. If you can change your literal datatype to one of RDF-compatible XSD datatypes, your object map should be e.g.

rr:objectMap[
            rr:template "POINT({lon},{lat});http://www.opengis.net/ref/def/crs/EPSG/0/4326";
            rr:datatype xsd:gYear;
         ];

This would return e.g.
"POINT(116.313862,40.010061);http://www.opengis.net/ref/def/crs/EPSG/0/4326"^^<http://www.w3.org/2001/XMLSchema#gYear>

Which is what I guess you want. So, long story short, what you ask (if I understand correctly) is not implemented. You would have to remove the datatype (after the ^^)

Alternatively, the source code could be modified fairly easily. I would try this:

In gr.seab.r2rml.beans.UtilImpl, you could change function findDataType not to exit when an unknown datatype is encountered. This means to change, from:

...
} else {
    		log.error("Found unknown datatype " + dataType);
    		System.exit(1);
    	}
		return null;
}
...
to
} else {
    		log.error("Found unknown datatype " + dataType);
    		return new BaseDatatype(dataType);
    	}
}
...

Please let me know how this goes, if this works for you, it would be nice to include it in the source code. Thanks again for your interest.

**Comment by nkons** [comment]
Also, to answer your question:

1. Is it possible to have rr:template to create result without automatically creating double quote " " ?

In short, no. Terms will be one of the following: Literals (enclosed in double quotes), URIs (enclosed in < and >), or Blank Nodes (with a blank node identifier).

The result is generated using the Jena library. This assures that the result will be at all times a valid RDF file. So, even if we try to output a string without enclosing it in double quotes, they will be added by Jena.

**Comment by nkons** [comment]
I just committed a small patch that I believe resolves this issue (much more easily than I expected). Please let me know how this goes.

**Comment by martinbog** [comment]
Thanks for the patch ! It works well. I compile your last committed version with eclipse. It is very easy.

**Comment by nkons** [comment]
I assume the parser mistakenly treats the template as a URI. In gr.seab.r2rml.entities.Template, a simple check to see whether a template contains a URI takes place:

		if (s.contains("http")) {
			return true;
		} else {
			return false;
		}

I believe you should change `s.contains` to `s.startsWith`.
