### ISSUE TITLE
R2RML rr:template and datetime (MySQL)

### ISSUE THREAD

**Issue by martinbog** [nkons/r2rml-parser#14]
Hi,

Another question : In my MySQL database I have a column of type datetime. I would like to use these temporal data in a rr:template in order to have an object like:
```
subject predicate <http://www.wstraj.com/trip/2009-05-01+03:52:08.0>
```
So I tried :

```
rr:predicateObjectMap [
        rr:predicate traj:trip ;
        rr:objectMap[
		rr:template 'http://www.wstraj.com/trip/{t}';
		rr:termType rr:IRI;
	];
].
```

All I got as result  :
```
traj:trip <2009-05-01+03%3A52%3A08.0> ; 
```
When I change my column type to text, I get the wanted translation : 

```
traj:trip <http://www.wstraj.com/trip/2009-05-01+03:52:08.0>.
```
Is there any implementation to use datetime type from MySQL in the parser ?

**Comment by nkons** [comment]
Hi Martin,

Since you get the wanted translation, I 'm happy it all works well.

Now, regarding datatypes from SQL: The generator tries to extract the SQL field datatype from the table metadata, when a mapping of a table is used instead of an SQL query view (i.e. use a `rr:logicalTable [ rr:tableName '"example"'; ];` instead of  `rr:logicalTable <#example-view>;`).

This happens in the gr.seab.r2rml.beans.Generator class: Look for findFieldDataType function, that calls findDataTypeFromSql function in gr.seab.r2rml.beans.UtilImpl.

So, if in the table metadata, a column is found to be "date", then type XSDDatatype.XSDdate should be returned.

All the above happen if a datatype was not assigned in the predicate-object map and the column mapped comes from a table (not an arbitrary sql query), but you could assign a datatype explicitly, using e.g rr:dataType xsd:dateTime.

Now, if the above do not work, you could change UtilImpl, from

    } else if (sqlDataType.equals("timestamp")
        			|| sqlDataType.equals("timestamptz")) {
            	return XSDDatatype.XSDdateTime;
to
    } else if (sqlDataType.equals("timestamp")
        			|| sqlDataType.equals("datetime")
        			|| sqlDataType.equals("timestamptz")) {
            	return XSDDatatype.XSDdateTime;
