### ISSUE TITLE
How to map TinyInt

### ISSUE THREAD

**Issue by chrissofvista** [nkons/r2rml-parser#22]
Hi,
in my R2RML mapping I have to address a column in a sql table that uses tinyint.
With my general mapping I get back "Found unknown SQL sqlDataType tinyint".
In my connection configuration with mysql jdbc driver I already use:
db.url = jdbc\:mysql\://myserver:3306/mydatabase?tinyInt1isBit=false
with no effect.
Any suggestions?

Best regards
Christian

**Comment by nkons** [comment]
Hi,

Thanks for reporting this. This happens because the tinyint type is not auto-detected. You can add it by adding the following line:

`|| sqlDataType.equals("tinyint") `

here: https://github.com/nkons/r2rml-parser/blob/master/src/main/java/gr/seab/r2rml/beans/UtilImpl.java#L331

Please let me know if this works for you.

Best regards,
Nikolaos

**Comment by chrissofvista** [comment]
Hi Nikolaos,
thanks for the information.
I have no clue from Java programming but I have installed my eclipse, loaded the maven project and inserted the line about tinyint.
But I get a problem with the POM file "Missing artifact com.oracle:ojdbc6:jar:11.2.0.3“
Any clue that could help me at this point?

Best regards
Christian

**Comment by nkons** [comment]
Hi Christian,

This is the oracle jdbc driver. Since you are not using oracle, there should be no problem if you comment out this dependency in pom.xml.

So, in this file:
https://github.com/nkons/r2rml-parser/blob/master/pom.xml
surround with comments or remove altogether the entry:

`<dependency>`
`  <groupId>com.oracle</groupId>`
`  <artifactId>ojdbc6</artifactId>`
`  <version>11.2.0.3</version>`
`</dependency>`

And then run `mvn package` again. I hope this solves the issue for now.

Best regards,
Nikolaos

**Comment by nkons** [comment]
Hi,

Happy that this could be sorted out. Thanks for your interest in this work.

Best regards,
Nikolaos
